<?xml version="1.0" encoding="US-ASCII" standalone="yes"?><?xml-stylesheet type="text/xsl" href="msi.xsl" ?><!--
      XML Dump of Windows Installer Database
      Created with msi2xml

      (C) 2001-2002 Daniel Gehriger (gehriger@linkcad.com)
--><!DOCTYPE msi [
   <!ELEMENT msi   (summary,table*)>
   <!ATTLIST msi version    CDATA #REQUIRED
                 xmlns:dt   CDATA #IMPLIED
                 msm        (yes|no) "no"
                 codepage   CDATA #IMPLIED
                 compression (MSZIP|LZX|none) "LZX">
   
   <!ELEMENT summary       (codepage?,title?,subject?,author?,keywords?,comments?,
                            template,lastauthor?,revnumber,lastprinted?,
                            createdtm?,lastsavedtm?,pagecount,wordcount,
                            charcount?,appname?,security?)>
                            
   <!ELEMENT codepage      (#PCDATA)>
   <!ELEMENT title         (#PCDATA)>
   <!ELEMENT subject       (#PCDATA)>
   <!ELEMENT author        (#PCDATA)>
   <!ELEMENT keywords      (#PCDATA)>
   <!ELEMENT comments      (#PCDATA)>
   <!ELEMENT template      (#PCDATA)>
   <!ELEMENT lastauthor    (#PCDATA)>
   <!ELEMENT revnumber     (#PCDATA)>
   <!ELEMENT lastprinted   (#PCDATA)>
   <!ELEMENT createdtm     (#PCDATA)>
   <!ELEMENT lastsavedtm   (#PCDATA)>
   <!ELEMENT pagecount     (#PCDATA)>
   <!ELEMENT wordcount     (#PCDATA)>
   <!ELEMENT charcount     (#PCDATA)>
   <!ELEMENT appname       (#PCDATA)>
   <!ELEMENT security      (#PCDATA)>                            
                                
   <!ELEMENT table         (col+,row*)>
   <!ATTLIST table
                name        CDATA #REQUIRED>

   <!ELEMENT col           (#PCDATA)>
   <!ATTLIST col
                 key       (yes|no) #IMPLIED
                 def       CDATA #IMPLIED>
                 
   <!ELEMENT row            (td+)>
   
   <!ELEMENT td             (#PCDATA)>
   <!ATTLIST td
                 href       CDATA #IMPLIED
                 dt:dt     (string|bin.base64) #IMPLIED
                 md5        CDATA #IMPLIED>
]><msi version="2.0" xmlns:dt="urn:schemas-microsoft-com:datatypes" codepage="1252">
	
	<summary>
		<codepage>1252</codepage>
		<title>dnetc</title>
		<subject>distributed computing client</subject>
		<author>Distributed Computing Technologies, Inc.</author>
		<keywords>distributed computing dnetc bovine cow rc5 ogr</keywords>
		<comments>cows are cool!</comments>
		<template>Intel;1033</template>
		<lastauthor>jlawson</lastauthor>
		<revnumber>{DBA3AAE0-AA73-40B3-B383-729C5F59B4E1}</revnumber>
		<lastprinted>09/12/2003 23:37</lastprinted>
		<createdtm>06/21/1999 02:00</createdtm>
		<lastsavedtm>06/13/2005 23:29</lastsavedtm>
		<pagecount>200</pagecount>
		<wordcount>2</wordcount>
		<charcount/>
		<appname>Windows Installer</appname>
		<security>1</security>
	</summary>
	
	<table name="ActionText">
		<col key="yes" def="s72">Action</col>
		<col def="L0">Description</col>
		<col def="L0">Template</col>
		<row>
			<td>Advertise</td>
			<td>Advertising application</td>
			<td/>
		</row>
		<row>
			<td>AllocateRegistrySpace</td>
			<td>Allocating registry space</td>
			<td>Free space: [1]</td>
		</row>
		<row>
			<td>AppSearch</td>
			<td>Searching for installed applications</td>
			<td>Property: [1], Signature: [2]</td>
		</row>
		<row>
			<td>BindImage</td>
			<td>Binding executables</td>
			<td>File: [1]</td>
		</row>
		<row>
			<td>CCPSearch</td>
			<td>Searching for qualifying products</td>
			<td/>
		</row>
		<row>
			<td>CostFinalize</td>
			<td>Computing space requirements</td>
			<td/>
		</row>
		<row>
			<td>CostInitialize</td>
			<td>Computing space requirements</td>
			<td/>
		</row>
		<row>
			<td>CreateFolders</td>
			<td>Creating folders</td>
			<td>Folder: [1]</td>
		</row>
		<row>
			<td>CreateShortcuts</td>
			<td>Creating shortcuts</td>
			<td>Shortcut: [1]</td>
		</row>
		<row>
			<td>DeleteServices</td>
			<td>Deleting services</td>
			<td>Service: [1]</td>
		</row>
		<row>
			<td>DuplicateFiles</td>
			<td>Creating duplicate files</td>
			<td>File: [1],  Directory: [9],  Size: [6]</td>
		</row>
		<row>
			<td>FileCost</td>
			<td>Computing space requirements</td>
			<td/>
		</row>
		<row>
			<td>GenerateScript</td>
			<td>Generating script operations for action:</td>
			<td>[1]</td>
		</row>
		<row>
			<td>InstallAdminPackage</td>
			<td>Copying network install files</td>
			<td>File: [1], Directory: [9], Size: [6]</td>
		</row>
		<row>
			<td>InstallFiles</td>
			<td>Copying new files</td>
			<td>File: [1],  Directory: [9],  Size: [6]</td>
		</row>
		<row>
			<td>InstallODBC</td>
			<td>Installing ODBC components</td>
			<td/>
		</row>
		<row>
			<td>InstallServices</td>
			<td>Installing new services</td>
			<td>Service: [2]</td>
		</row>
		<row>
			<td>InstallValidate</td>
			<td>Validating install</td>
			<td/>
		</row>
		<row>
			<td>LaunchConditions</td>
			<td>Evaluating launch conditions</td>
			<td/>
		</row>
		<row>
			<td>MoveFiles</td>
			<td>Moving files</td>
			<td>File: [1],  Directory: [9],  Size: [6]</td>
		</row>
		<row>
			<td>PatchFiles</td>
			<td>Patching files</td>
			<td>File: [1],  Directory: [2],  Size: [3]</td>
		</row>
		<row>
			<td>ProcessComponents</td>
			<td>Updating component registration</td>
			<td/>
		</row>
		<row>
			<td>PublishComponents</td>
			<td>Publishing Qualified Components</td>
			<td>Component ID: [1], Qualifier: [2]</td>
		</row>
		<row>
			<td>PublishFeatures</td>
			<td>Publishing Product Features</td>
			<td>Feature: [1]</td>
		</row>
		<row>
			<td>PublishProduct</td>
			<td>Publishing product information</td>
			<td/>
		</row>
		<row>
			<td>RMCCPSearch</td>
			<td>Searching for qualifying products</td>
			<td/>
		</row>
		<row>
			<td>RUNCA_CONFIG_DNETC</td>
			<td>Waiting for client configuration to complete before continuing...</td>
			<td/>
		</row>
		<row>
			<td>RUNCA_INSTALL_DNETC</td>
			<td>Installing client as service</td>
			<td/>
		</row>
		<row>
			<td>RUNCA_KILLRUNNINGCLIENTWINDOWS</td>
			<td>Stopping running clients</td>
			<td/>
		</row>
		<row>
			<td>RUNCA_STOP_DNETC</td>
			<td>Stopping running clients</td>
			<td/>
		</row>
		<row>
			<td>RUNCA_UNINST_DNETC</td>
			<td>Removing client service</td>
			<td/>
		</row>
		<row>
			<td>RegisterClassInfo</td>
			<td>Registering Class servers</td>
			<td>Class Id: [1]</td>
		</row>
		<row>
			<td>RegisterExtensionInfo</td>
			<td>Registering extension servers</td>
			<td>Extension: [1]</td>
		</row>
		<row>
			<td>RegisterFonts</td>
			<td>Registering fonts</td>
			<td>Font: [1]</td>
		</row>
		<row>
			<td>RegisterMIMEInfo</td>
			<td>Registering MIME info</td>
			<td>MIME Content Type: [1], Extension: [2]</td>
		</row>
		<row>
			<td>RegisterProduct</td>
			<td>Registering product</td>
			<td>[1]</td>
		</row>
		<row>
			<td>RegisterProgIdInfo</td>
			<td>Unregistering program identifiers</td>
			<td>ProgId: [1]</td>
		</row>
		<row>
			<td>RegisterTypeLibraries</td>
			<td>Registering type libraries</td>
			<td>LibID: [1]</td>
		</row>
		<row>
			<td>RegisterUser</td>
			<td>Registering user</td>
			<td>[1]</td>
		</row>
		<row>
			<td>RemoveDuplicateFiles</td>
			<td>Removing duplicated files</td>
			<td>File: [1], Directory: [9]</td>
		</row>
		<row>
			<td>RemoveEnvironmentStrings</td>
			<td>Updating environment strings</td>
			<td>Name: [1], Value: [2], Action [3]</td>
		</row>
		<row>
			<td>RemoveFiles</td>
			<td>Removing files</td>
			<td>File: [1], Directory: [9]</td>
		</row>
		<row>
			<td>RemoveFolders</td>
			<td>Removing folders</td>
			<td>Folder: [1]</td>
		</row>
		<row>
			<td>RemoveIniValues</td>
			<td>Removing INI files entries</td>
			<td>File: [1],  Section: [2],  Key: [3], Value: [4]</td>
		</row>
		<row>
			<td>RemoveODBC</td>
			<td>Removing ODBC components</td>
			<td/>
		</row>
		<row>
			<td>RemoveRegistryValues</td>
			<td>Removing system registry values</td>
			<td>Key: [1], Name: [2]</td>
		</row>
		<row>
			<td>RemoveShortcuts</td>
			<td>Removing shortcuts</td>
			<td>Shortcut: [1]</td>
		</row>
		<row>
			<td>Rollback</td>
			<td>Rolling back action:</td>
			<td>[1]</td>
		</row>
		<row>
			<td>RollbackCleanup</td>
			<td>Finalizing installation and waiting for configuration...</td>
			<td/>
		</row>
		<row>
			<td>SelfRegModules</td>
			<td>Registering modules</td>
			<td>File: [1], Folder: [2]</td>
		</row>
		<row>
			<td>SelfUnregModules</td>
			<td>Unregistering modules</td>
			<td>File: [1], Folder: [2]</td>
		</row>
		<row>
			<td>SetODBCFolders</td>
			<td>Initializing ODBC directories</td>
			<td>ODBC Driver [1] forcing folder [2] to [3]</td>
		</row>
		<row>
			<td>StartServices</td>
			<td>Starting services</td>
			<td>Service: [1]</td>
		</row>
		<row>
			<td>StopServices</td>
			<td>Stopping services</td>
			<td>Service: [1]</td>
		</row>
		<row>
			<td>UnmoveFiles</td>
			<td>Removing moved files</td>
			<td>File: [1], Directory: [9]</td>
		</row>
		<row>
			<td>UnpublishComponents</td>
			<td>Unpublishing Qualified Components</td>
			<td>Component ID: [1], Qualifier: [2]</td>
		</row>
		<row>
			<td>UnpublishFeatures</td>
			<td>Unpublishing Product Features</td>
			<td>Feature: [1]</td>
		</row>
		<row>
			<td>UnpublishProduct</td>
			<td>Unpublishing product information</td>
			<td/>
		</row>
		<row>
			<td>UnregisterClassInfo</td>
			<td>Unregister Class servers</td>
			<td>Class Id: [1]</td>
		</row>
		<row>
			<td>UnregisterExtensionInfo</td>
			<td>Unregistering extension servers</td>
			<td>Extension: [1]</td>
		</row>
		<row>
			<td>UnregisterFonts</td>
			<td>Unregistering fonts</td>
			<td>Font: [1]</td>
		</row>
		<row>
			<td>UnregisterMIMEInfo</td>
			<td>Unregistering MIME info</td>
			<td>MIME Content Type: [1], Extension: [2]</td>
		</row>
		<row>
			<td>UnregisterProgIdInfo</td>
			<td>Unregistering program identifiers</td>
			<td>ProgId: [1]</td>
		</row>
		<row>
			<td>UnregisterTypeLibraries</td>
			<td>Unregistering type libraries</td>
			<td>LibID: [1]</td>
		</row>
		<row>
			<td>WriteEnvironmentStrings</td>
			<td>Updating environment strings</td>
			<td>Name: [1], Value: [2], Action [3]</td>
		</row>
		<row>
			<td>WriteIniValues</td>
			<td>Writing INI files values</td>
			<td>File: [1],  Section: [2],  Key: [3], Value: [4]</td>
		</row>
		<row>
			<td>WriteRegistryValues</td>
			<td>Writing system registry values</td>
			<td>Key: [1], Name: [2], Value: [3]</td>
		</row>
	</table>

	<table name="AdminExecuteSequence">
		<col key="yes" def="s72">Action</col>
		<col def="S255">Condition</col>
		<col def="I2">Sequence</col>
		<row>
			<td>CostFinalize</td>
			<td/>
			<td>1000</td>
		</row>
		<row>
			<td>CostInitialize</td>
			<td/>
			<td>800</td>
		</row>
		<row>
			<td>DIRCA_TARGETDIR</td>
			<td>TARGETDIR=""</td>
			<td>750</td>
		</row>
		<row>
			<td>FileCost</td>
			<td/>
			<td>900</td>
		</row>
		<row>
			<td>InstallAdminPackage</td>
			<td/>
			<td>3900</td>
		</row>
		<row>
			<td>InstallFiles</td>
			<td/>
			<td>4000</td>
		</row>
		<row>
			<td>InstallFinalize</td>
			<td/>
			<td>6600</td>
		</row>
		<row>
			<td>InstallInitialize</td>
			<td/>
			<td>1500</td>
		</row>
		<row>
			<td>InstallValidate</td>
			<td/>
			<td>1400</td>
		</row>
	</table>

	<table name="AdminUISequence">
		<col key="yes" def="s72">Action</col>
		<col def="S255">Condition</col>
		<col def="I2">Sequence</col>
		<row>
			<td>AdminFatalErrorForm</td>
			<td/>
			<td>-3</td>
		</row>
		<row>
			<td>AdminFinishedForm</td>
			<td/>
			<td>-1</td>
		</row>
		<row>
			<td>AdminMaintenanceForm</td>
			<td>Installed&lt;&gt;""</td>
			<td>999</td>
		</row>
		<row>
			<td>AdminProgressForm</td>
			<td/>
			<td>1299</td>
		</row>
		<row>
			<td>AdminResumeForm</td>
			<td>Installed="" AND RESUME</td>
			<td>998</td>
		</row>
		<row>
			<td>AdminUserExitForm</td>
			<td/>
			<td>-2</td>
		</row>
		<row>
			<td>AdminWelcomeForm</td>
			<td>Installed="" AND NOT RESUME</td>
			<td>1001</td>
		</row>
		<row>
			<td>CostFinalize</td>
			<td/>
			<td>1000</td>
		</row>
		<row>
			<td>CostInitialize</td>
			<td/>
			<td>800</td>
		</row>
		<row>
			<td>DIRCA_TARGETDIR</td>
			<td>TARGETDIR=""</td>
			<td>750</td>
		</row>
		<row>
			<td>ExecuteAction</td>
			<td/>
			<td>1300</td>
		</row>
		<row>
			<td>FileCost</td>
			<td/>
			<td>900</td>
		</row>
	</table>

	<table name="AdvtExecuteSequence">
		<col key="yes" def="s72">Action</col>
		<col def="S255">Condition</col>
		<col def="I2">Sequence</col>
		<row>
			<td>CostFinalize</td>
			<td/>
			<td>1000</td>
		</row>
		<row>
			<td>CostInitialize</td>
			<td/>
			<td>800</td>
		</row>
		<row>
			<td>CreateShortcuts</td>
			<td/>
			<td>4500</td>
		</row>
		<row>
			<td>InstallFinalize</td>
			<td/>
			<td>6600</td>
		</row>
		<row>
			<td>InstallInitialize</td>
			<td/>
			<td>1500</td>
		</row>
		<row>
			<td>InstallValidate</td>
			<td/>
			<td>1400</td>
		</row>
		<row>
			<td>MsiPublishAssemblies</td>
			<td/>
			<td>6250</td>
		</row>
		<row>
			<td>MsiUnpublishAssemblies</td>
			<td/>
			<td>1650</td>
		</row>
		<row>
			<td>PublishComponents</td>
			<td/>
			<td>6200</td>
		</row>
		<row>
			<td>PublishFeatures</td>
			<td/>
			<td>6300</td>
		</row>
		<row>
			<td>PublishProduct</td>
			<td/>
			<td>6400</td>
		</row>
		<row>
			<td>RegisterClassInfo</td>
			<td/>
			<td>4600</td>
		</row>
		<row>
			<td>RegisterExtensionInfo</td>
			<td/>
			<td>4700</td>
		</row>
		<row>
			<td>RegisterMIMEInfo</td>
			<td/>
			<td>4900</td>
		</row>
		<row>
			<td>RegisterProgIdInfo</td>
			<td/>
			<td>4800</td>
		</row>
	</table>

	<table name="AdvtUISequence">
		<col key="yes" def="s72">Action</col>
		<col def="S255">Condition</col>
		<col def="I2">Sequence</col>
	</table>

	<table name="AppSearch">
		<col key="yes" def="s72">Property</col>
		<col key="yes" def="s72">Signature_</col>
		<row>
			<td>PERSONAL_SCREEN_SAVER</td>
			<td>Signature_reg_personal_saver</td>
		</row>
		<row>
			<td>TARGETDIR</td>
			<td>Signature_reg_mru_client</td>
		</row>
	</table>

	<table name="Binary">
		<col key="yes" def="s72">Name</col>
		<col def="v0">Data</col>
		<row>
			<td>BannerBitmap.bmp</td>
			<td href="streams/Binary.BannerBitmap.bmp" md5="7d1ceeec5743cecdad26afc29cfe103d"/>
		</row>
		<row>
			<td>MsiLib.dll</td>
			<td href="streams/Binary.MsiLib.dll" md5="b8135a78a6eb1525a8b7129f8b988956"/>
		</row>
		<row>
			<td>NewFldrBtn.bmp</td>
			<td href="streams/Binary.NewFldrBtn.bmp" md5="326a40f5ae0f716a3818531e475678bf"/>
		</row>
		<row>
			<td>UpFldrBtn.bmp</td>
			<td href="streams/Binary.UpFldrBtn.bmp" md5="4638b2aa55fbd0fa73bb08181895cbe7"/>
		</row>
	</table>

	<table name="CCPSearch">
		<col key="yes" def="s72">Signature_</col>
	</table>

	<table name="CheckBox">
		<col key="yes" def="s72">Property</col>
		<col def="S64">Value</col>
		<row>
			<td>DNETC_RUNCONFIG</td>
			<td>1</td>
		</row>
	</table>

	<table name="ComboBox">
		<col key="yes" def="s72">Property</col>
		<col key="yes" def="i2">Order</col>
		<col def="s64">Value</col>
		<col def="L64">Text</col>
	</table>

	<table name="CompLocator">
		<col key="yes" def="s72">Signature_</col>
		<col def="s38">ComponentId</col>
		<col def="I2">Type</col>
	</table>

	<table name="Component">
		<col key="yes" def="s72">Component</col>
		<col def="S38">ComponentId</col>
		<col def="s72">Directory_</col>
		<col def="i2">Attributes</col>
		<col def="S255">Condition</col>
		<col def="S72">KeyPath</col>
		<row>
			<td>ComponentClient</td>
			<td>{C63D2AF1-8847-2346-1285-A5A9C38DDA97}</td>
			<td>TARGETDIR</td>
			<td>0</td>
			<td>1</td>
			<td>dnetc.exe</td>
		</row>
		<row>
			<td>ComponentClientShortcuts</td>
			<td>{CD30EE5D-8C2B-4149-ABD8-1B615C02FAEE}</td>
			<td>TARGETDIR</td>
			<td>4</td>
			<td>1</td>
			<td>Registry008</td>
		</row>
		<row>
			<td>ComponentDocs</td>
			<td>{59A7D992-3A4A-41D1-3ED7-FDB1305A3185}</td>
			<td>TARGETDIR</td>
			<td>0</td>
			<td>1</td>
			<td>changes.txt</td>
		</row>
		<row>
			<td>ComponentDocsShortcuts</td>
			<td>{621CF062-519B-4B40-850B-39CEC7067D13}</td>
			<td>TARGETDIR</td>
			<td>4</td>
			<td>1</td>
			<td>Registry007</td>
		</row>
		<row>
			<td>ComponentRunAllUsersStartup</td>
			<td>{56801C97-87FD-4164-AE05-1E9D3F1DF094}</td>
			<td>TARGETDIR</td>
			<td>4</td>
			<td>DNETC_STARTMODE="AllStartup"</td>
			<td>Registry006</td>
		</row>
		<row>
			<td>ComponentRunMyUserSaver</td>
			<td>{DC4E20A2-92DD-422D-AEE9-3C9DD28035A9}</td>
			<td>TARGETDIR</td>
			<td>4</td>
			<td>DNETC_STARTMODE="MySaver"</td>
			<td>Registry002</td>
		</row>
		<row>
			<td>ComponentRunService</td>
			<td>{971F97C6-D724-4D25-82B5-4992D6236281}</td>
			<td>TARGETDIR</td>
			<td>4</td>
			<td>DNETC_STARTMODE="Service"</td>
			<td>Registry004</td>
		</row>
		<row>
			<td>ComponentSaver</td>
			<td>{97C77586-1324-22EF-BABF-9F3DCE288FF3}</td>
			<td>TARGETDIR</td>
			<td>0</td>
			<td>1</td>
			<td>dnetc.scr</td>
		</row>
		<row>
			<td>RemoveObsolete</td>
			<td>{B1D64897-5037-4893-8C3E-0B4B389CD406}</td>
			<td>TARGETDIR</td>
			<td>4</td>
			<td>1</td>
			<td>Registry009</td>
		</row>
	</table>

	<table name="Condition">
		<col key="yes" def="s38">Feature_</col>
		<col key="yes" def="i2">Level</col>
		<col def="S255">Condition</col>
	</table>

	<table name="Control">
		<col key="yes" def="s72">Dialog_</col>
		<col key="yes" def="s50">Control</col>
		<col def="s20">Type</col>
		<col def="i2">X</col>
		<col def="i2">Y</col>
		<col def="i2">Width</col>
		<col def="i2">Height</col>
		<col def="I4">Attributes</col>
		<col def="S50">Property</col>
		<col def="L0">Text</col>
		<col def="S50">Control_Next</col>
		<col def="L50">Help</col>
		<row>
			<td>AdminConfirmInstallForm</td>
			<td>BannerBmp</td>
			<td>Bitmap</td>
			<td>0</td>
			<td>0</td>
			<td>375</td>
			<td>52</td>
			<td>1</td>
			<td/>
			<td>[SFF_DefBannerBitmap]</td>
			<td>NextButton</td>
			<td>|</td>
		</row>
		<row>
			<td>AdminConfirmInstallForm</td>
			<td>BannerText</td>
			<td>Text</td>
			<td>9</td>
			<td>9</td>
			<td>306</td>
			<td>33</td>
			<td>65539</td>
			<td/>
			<td>{\VSI_MS_Sans_Serif16.0_1_0}Confirm Installation</td>
			<td/>
			<td>|</td>
		</row>
		<row>
			<td>AdminConfirmInstallForm</td>
			<td>BodyText1</td>
			<td>Text</td>
			<td>9</td>
			<td>63</td>
			<td>354</td>
			<td>180</td>
			<td>3</td>
			<td/>
			<td>{\VSI_MS_Sans_Serif13.0_0_0}The installer is ready to install [ProductName] on your computer.

Click "Next" to start the installation.</td>
			<td/>
			<td>|</td>
		</row>
		<row>
			<td>AdminConfirmInstallForm</td>
			<td>CancelButton</td>
			<td>PushButton</td>
			<td>156</td>
			<td>261</td>
			<td>66</td>
			<td>18</td>
			<td>3</td>
			<td/>
			<td>{\VSI_MS_Sans_Serif13.0_0_0}Cancel</td>
			<td>PreviousButton</td>
			<td>|</td>
		</row>
		<row>
			<td>AdminConfirmInstallForm</td>
			<td>Line1</td>
			<td>Line</td>
			<td>0</td>
			<td>52</td>
			<td>375</td>
			<td>6</td>
			<td>1</td>
			<td/>
			<td>{\VSI_MS_Sans_Serif13.0_0_0}MsiHorizontalLine</td>
			<td/>
			<td>|</td>
		</row>
		<row>
			<td>AdminConfirmInstallForm</td>
			<td>Line2</td>
			<td>Line</td>
			<td>0</td>
			<td>252</td>
			<td>375</td>
			<td>6</td>
			<td>1</td>
			<td/>
			<td>{\VSI_MS_Sans_Serif13.0_0_0}MsiHorizontalLine</td>
			<td/>
			<td>|</td>
		</row>
		<row>
			<td>AdminConfirmInstallForm</td>
			<td>NextButton</td>
			<td>PushButton</td>
			<td>300</td>
			<td>261</td>
			<td>66</td>
			<td>18</td>
			<td>3</td>
			<td/>
			<td>{\VSI_MS_Sans_Serif13.0_0_0}&amp;Next &gt;</td>
			<td>CancelButton</td>
			<td>|</td>
		</row>
		<row>
			<td>AdminConfirmInstallForm</td>
			<td>PreviousButton</td>
			<td>PushButton</td>
			<td>228</td>
			<td>261</td>
			<td>66</td>
			<td>18</td>
			<td>3</td>
			<td/>
			<td>{\VSI_MS_Sans_Serif13.0_0_0}&lt; &amp;Back</td>
			<td>BannerBmp</td>
			<td>|</td>
		</row>
		<row>
			<td>AdminFatalErrorForm</td>
			<td>BannerBmp</td>
			<td>Bitmap</td>
			<td>0</td>
			<td>0</td>
			<td>375</td>
			<td>52</td>
			<td>1</td>
			<td/>
			<td>[SFF_DefBannerBitmap]</td>
			<td>CloseButton</td>
			<td>|</td>
		</row>
		<row>
			<td>AdminFatalErrorForm</td>
			<td>BannerText</td>
			<td>Text</td>
			<td>9</td>
			<td>9</td>
			<td>306</td>
			<td>33</td>
			<td>65539</td>
			<td/>
			<td>{\VSI_MS_Sans_Serif16.0_1_0}Installation Incomplete</td>
			<td/>
			<td>|</td>
		</row>
		<row>
			<td>AdminFatalErrorForm</td>
			<td>BodyTextInstall</td>
			<td>Text</td>
			<td>9</td>
			<td>63</td>
			<td>354</td>
			<td>180</td>
			<td>3</td>
			<td/>
			<td>{\VSI_MS_Sans_Serif13.0_0_0}The installer was interrupted before [ProductName] could be removed. You need to restart the installer to try again.

Click "Close" to exit.</td>
			<td/>
			<td>|</td>
		</row>
		<row>
			<td>AdminFatalErrorForm</td>
			<td>BodyTextRemove</td>
			<td>Text</td>
			<td>9</td>
			<td>63</td>
			<td>354</td>
			<td>180</td>
			<td>3</td>
			<td/>
			<td>{\VSI_MS_Sans_Serif13.0_0_0}The installer was interrupted before [ProductName] could be installed. You need to restart the installer to try again.

Click "Close" to exit.</td>
			<td/>
			<td>|</td>
		</row>
		<row>
			<td>AdminFatalErrorForm</td>
			<td>CancelButton</td>
			<td>PushButton</td>
			<td>156</td>
			<td>261</td>
			<td>66</td>
			<td>18</td>
			<td>1</td>
			<td/>
			<td>{\VSI_MS_Sans_Serif13.0_0_0}Cancel</td>
			<td>PreviousButton</td>
			<td>|</td>
		</row>
		<row>
			<td>AdminFatalErrorForm</td>
			<td>CloseButton</td>
			<td>PushButton</td>
			<td>300</td>
			<td>261</td>
			<td>66</td>
			<td>18</td>
			<td>3</td>
			<td/>
			<td>{\VSI_MS_Sans_Serif13.0_0_0}&amp;Close</td>
			<td>CancelButton</td>
			<td>|</td>
		</row>
		<row>
			<td>AdminFatalErrorForm</td>
			<td>Line1</td>
			<td>Line</td>
			<td>0</td>
			<td>52</td>
			<td>375</td>
			<td>6</td>
			<td>1</td>
			<td/>
			<td>{\VSI_MS_Sans_Serif13.0_0_0}MsiHorizontalLine</td>
			<td/>
			<td>|</td>
		</row>
		<row>
			<td>AdminFatalErrorForm</td>
			<td>Line2</td>
			<td>Line</td>
			<td>0</td>
			<td>252</td>
			<td>375</td>
			<td>6</td>
			<td>1</td>
			<td/>
			<td>{\VSI_MS_Sans_Serif13.0_0_0}MsiHorizontalLine</td>
			<td/>
			<td>|</td>
		</row>
		<row>
			<td>AdminFatalErrorForm</td>
			<td>PreviousButton</td>
			<td>PushButton</td>
			<td>228</td>
			<td>261</td>
			<td>66</td>
			<td>18</td>
			<td>1</td>
			<td/>
			<td>{\VSI_MS_Sans_Serif13.0_0_0}&lt; &amp;Back</td>
			<td>BannerBmp</td>
			<td>|</td>
		</row>
		<row>
			<td>AdminFinishedForm</td>
			<td>BannerBmp</td>
			<td>Bitmap</td>
			<td>0</td>
			<td>0</td>
			<td>375</td>
			<td>52</td>
			<td>1</td>
			<td/>
			<td>[SFF_DefBannerBitmap]</td>
			<td>CloseButton</td>
			<td>|</td>
		</row>
		<row>
			<td>AdminFinishedForm</td>
			<td>BannerText</td>
			<td>Text</td>
			<td>9</td>
			<td>9</td>
			<td>306</td>
			<td>33</td>
			<td>65539</td>
			<td/>
			<td>{\VSI_MS_Sans_Serif16.0_1_0}Installation Complete</td>
			<td/>
			<td>|</td>
		</row>
		<row>
			<td>AdminFinishedForm</td>
			<td>BodyText</td>
			<td>Text</td>
			<td>9</td>
			<td>63</td>
			<td>354</td>
			<td>180</td>
			<td>3</td>
			<td/>
			<td>{\VSI_MS_Sans_Serif13.0_0_0}[ProductName] has been successfully removed.

Click "Close" to exit.</td>
			<td/>
			<td>|</td>
		</row>
		<row>
			<td>AdminFinishedForm</td>
			<td>BodyTextInstall</td>
			<td>Text</td>
			<td>9</td>
			<td>63</td>
			<td>354</td>
			<td>180</td>
			<td>3</td>
			<td/>
			<td>{\VSI_MS_Sans_Serif13.0_0_0}A network image of [ProductName] has been successfully created.

Click "Close" to exit.</td>
			<td/>
			<td>|</td>
		</row>
		<row>
			<td>AdminFinishedForm</td>
			<td>CancelButton</td>
			<td>PushButton</td>
			<td>156</td>
			<td>261</td>
			<td>66</td>
			<td>18</td>
			<td>1</td>
			<td/>
			<td>{\VSI_MS_Sans_Serif13.0_0_0}Cancel</td>
			<td>PreviousButton</td>
			<td>|</td>
		</row>
		<row>
			<td>AdminFinishedForm</td>
			<td>CloseButton</td>
			<td>PushButton</td>
			<td>300</td>
			<td>261</td>
			<td>66</td>
			<td>18</td>
			<td>3</td>
			<td/>
			<td>{\VSI_MS_Sans_Serif13.0_0_0}&amp;Close</td>
			<td>CancelButton</td>
			<td>|</td>
		</row>
		<row>
			<td>AdminFinishedForm</td>
			<td>Line1</td>
			<td>Line</td>
			<td>0</td>
			<td>52</td>
			<td>375</td>
			<td>6</td>
			<td>1</td>
			<td/>
			<td>{\VSI_MS_Sans_Serif13.0_0_0}MsiHorizontalLine</td>
			<td/>
			<td>|</td>
		</row>
		<row>
			<td>AdminFinishedForm</td>
			<td>Line2</td>
			<td>Line</td>
			<td>0</td>
			<td>252</td>
			<td>375</td>
			<td>6</td>
			<td>1</td>
			<td/>
			<td>{\VSI_MS_Sans_Serif13.0_0_0}MsiHorizontalLine</td>
			<td/>
			<td>|</td>
		</row>
		<row>
			<td>AdminFinishedForm</td>
			<td>PreviousButton</td>
			<td>PushButton</td>
			<td>228</td>
			<td>261</td>
			<td>66</td>
			<td>18</td>
			<td>1</td>
			<td/>
			<td>{\VSI_MS_Sans_Serif13.0_0_0}&lt; &amp;Back</td>
			<td>BannerBmp</td>
			<td>|</td>
		</row>
		<row>
			<td>AdminFolderForm</td>
			<td>BannerBmp</td>
			<td>Bitmap</td>
			<td>0</td>
			<td>0</td>
			<td>375</td>
			<td>52</td>
			<td>1</td>
			<td/>
			<td>[SFF_DefBannerBitmap]</td>
			<td>NextButton</td>
			<td>|</td>
		</row>
		<row>
			<td>AdminFolderForm</td>
			<td>BannerText</td>
			<td>Text</td>
			<td>9</td>
			<td>9</td>
			<td>306</td>
			<td>33</td>
			<td>65539</td>
			<td/>
			<td>{\VSI_MS_Sans_Serif16.0_1_0}Network Location</td>
			<td/>
			<td>|</td>
		</row>
		<row>
			<td>AdminFolderForm</td>
			<td>Body</td>
			<td>Text</td>
			<td>9</td>
			<td>63</td>
			<td>354</td>
			<td>48</td>
			<td>3</td>
			<td/>
			<td>{\VSI_MS_Sans_Serif13.0_0_0}The installer will create a network image at the following location.

To create an image in this folder, click "Next". To use a different folder, enter it below or click "Browse".</td>
			<td/>
			<td>|</td>
		</row>
		<row>
			<td>AdminFolderForm</td>
			<td>BrowseButton</td>
			<td>PushButton</td>
			<td>282</td>
			<td>126</td>
			<td>84</td>
			<td>18</td>
			<td>3</td>
			<td/>
			<td>{\VSI_MS_Sans_Serif13.0_0_0}B&amp;rowse...</td>
			<td>DiskCostButton</td>
			<td>|</td>
		</row>
		<row>
			<td>AdminFolderForm</td>
			<td>CancelButton</td>
			<td>PushButton</td>
			<td>156</td>
			<td>261</td>
			<td>66</td>
			<td>18</td>
			<td>3</td>
			<td/>
			<td>{\VSI_MS_Sans_Serif13.0_0_0}Cancel</td>
			<td>PreviousButton</td>
			<td>|</td>
		</row>
		<row>
			<td>AdminFolderForm</td>
			<td>DiskCostButton</td>
			<td>PushButton</td>
			<td>282</td>
			<td>150</td>
			<td>84</td>
			<td>18</td>
			<td>3</td>
			<td/>
			<td>{\VSI_MS_Sans_Serif13.0_0_0}&amp;Disk Cost...</td>
			<td>CancelButton</td>
			<td>|</td>
		</row>
		<row>
			<td>AdminFolderForm</td>
			<td>FolderEdit</td>
			<td>PathEdit</td>
			<td>18</td>
			<td>126</td>
			<td>258</td>
			<td>18</td>
			<td>7</td>
			<td>TARGETDIR</td>
			<td>{\VSI_MS_Sans_Serif13.0_0_0}MsiPathEdit</td>
			<td>BrowseButton</td>
			<td>|</td>
		</row>
		<row>
			<td>AdminFolderForm</td>
			<td>FolderLabel</td>
			<td>Text</td>
			<td>18</td>
			<td>114</td>
			<td>348</td>
			<td>12</td>
			<td>3</td>
			<td/>
			<td>{\VSI_MS_Sans_Serif13.0_0_0}&amp;Folder:</td>
			<td>FolderEdit</td>
			<td>|</td>
		</row>
		<row>
			<td>AdminFolderForm</td>
			<td>Line1</td>
			<td>Line</td>
			<td>0</td>
			<td>52</td>
			<td>375</td>
			<td>6</td>
			<td>1</td>
			<td/>
			<td>{\VSI_MS_Sans_Serif13.0_0_0}MsiHorizontalLine</td>
			<td/>
			<td>|</td>
		</row>
		<row>
			<td>AdminFolderForm</td>
			<td>Line2</td>
			<td>Line</td>
			<td>0</td>
			<td>252</td>
			<td>375</td>
			<td>6</td>
			<td>1</td>
			<td/>
			<td>{\VSI_MS_Sans_Serif13.0_0_0}MsiHorizontalLine</td>
			<td/>
			<td>|</td>
		</row>
		<row>
			<td>AdminFolderForm</td>
			<td>NextButton</td>
			<td>PushButton</td>
			<td>300</td>
			<td>261</td>
			<td>66</td>
			<td>18</td>
			<td>3</td>
			<td/>
			<td>{\VSI_MS_Sans_Serif13.0_0_0}&amp;Next &gt;</td>
			<td>FolderLabel</td>
			<td>|</td>
		</row>
		<row>
			<td>AdminFolderForm</td>
			<td>PreviousButton</td>
			<td>PushButton</td>
			<td>228</td>
			<td>261</td>
			<td>66</td>
			<td>18</td>
			<td>3</td>
			<td/>
			<td>{\VSI_MS_Sans_Serif13.0_0_0}&lt; &amp;Back</td>
			<td>BannerBmp</td>
			<td>|</td>
		</row>
		<row>
			<td>AdminMaintenanceForm</td>
			<td>BannerBmp</td>
			<td>Bitmap</td>
			<td>0</td>
			<td>0</td>
			<td>375</td>
			<td>52</td>
			<td>1</td>
			<td/>
			<td>[SFF_DefBannerBitmap]</td>
			<td>FinishButton</td>
			<td>|</td>
		</row>
		<row>
			<td>AdminMaintenanceForm</td>
			<td>BannerText</td>
			<td>Text</td>
			<td>9</td>
			<td>9</td>
			<td>306</td>
			<td>33</td>
			<td>65539</td>
			<td/>
			<td>{\VSI_MS_Sans_Serif16.0_1_0}Welcome to the [ProductName] Setup Wizard</td>
			<td/>
			<td>|</td>
		</row>
		<row>
			<td>AdminMaintenanceForm</td>
			<td>BodyText</td>
			<td>Text</td>
			<td>9</td>
			<td>63</td>
			<td>354</td>
			<td>42</td>
			<td>3</td>
			<td/>
			<td>{\VSI_MS_Sans_Serif13.0_0_0}Select whether you want to repair or remove [ProductName].</td>
			<td/>
			<td>|</td>
		</row>
		<row>
			<td>AdminMaintenanceForm</td>
			<td>CancelButton</td>
			<td>PushButton</td>
			<td>156</td>
			<td>261</td>
			<td>66</td>
			<td>18</td>
			<td>3</td>
			<td/>
			<td>{\VSI_MS_Sans_Serif13.0_0_0}Cancel</td>
			<td>PreviousButton</td>
			<td>|</td>
		</row>
		<row>
			<td>AdminMaintenanceForm</td>
			<td>FinishButton</td>
			<td>PushButton</td>
			<td>300</td>
			<td>261</td>
			<td>66</td>
			<td>18</td>
			<td>3</td>
			<td/>
			<td>{\VSI_MS_Sans_Serif13.0_0_0}&amp;Finish</td>
			<td>RepairRadioGroup</td>
			<td>|</td>
		</row>
		<row>
			<td>AdminMaintenanceForm</td>
			<td>Line1</td>
			<td>Line</td>
			<td>0</td>
			<td>52</td>
			<td>375</td>
			<td>6</td>
			<td>1</td>
			<td/>
			<td>{\VSI_MS_Sans_Serif13.0_0_0}MsiHorizontalLine</td>
			<td/>
			<td>|</td>
		</row>
		<row>
			<td>AdminMaintenanceForm</td>
			<td>Line2</td>
			<td>Line</td>
			<td>0</td>
			<td>252</td>
			<td>375</td>
			<td>6</td>
			<td>1</td>
			<td/>
			<td>{\VSI_MS_Sans_Serif13.0_0_0}MsiHorizontalLine</td>
			<td/>
			<td>|</td>
		</row>
		<row>
			<td>AdminMaintenanceForm</td>
			<td>PreviousButton</td>